spring:
  datasource:
    url: jdbc:mysql://localhost:3306/location_system?useUnicode=trueuse&characterEncoding=UTF-8useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #以下为连接池的相关参数配置
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 50
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      connection-test-query: SELECT 1
    tomcat:
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    dbcp2:
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      #spring.datasource.test-on-borrow=false
            #指明是否从池中取出连接前进行检验，如果检验失败，则从池中取出连接并尝试取出另一个
             #spring.datasource.test-while-idle=true
             #指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除。
             #spring.datasource.time-between-eviction-runs-millis= 18800
             #在空闲连接回收器线程运行期间休眠的时间值，以毫秒为单位。如果设置为非整数，则不运行空闲连接回收器线程

  servlet:
    multipart:
    # Single file max size  即单个文件大小
      max-file-size: 10MB
    # All files max size      即总上传的数据大小
      max-request-size: 100MB




server:
  port: 9999
  tomcat:
    max-http-header-size: 8192
    remote-ip-header: x-forward-for
    uri-encoding: utf-8
    max-threads: 1000
  connection-timeout: 20000


logging:
  file: d:\log\locationlog\location.log
  level:
      root: info
      com.tg.locationsystem.mapper: ERROR
#日志级别:TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF

# 异步线程配置
# 配置核心线程数
#async.executor.thread.core_pool_size = 8
async:
  executor:
    thread:
      core_pool_size: 8
      max_pool_size: 20
# 配置最大线程数
#async.executor.thread.max_pool_size = 20
# 配置队列大小
#async.executor.thread.queue_capacity = 99999
# 配置线程池中的线程的名称前缀
#async.executor.thread.name.prefix = async-service-
